#!/bin/bash
cd /tmp/rom # Depends on where source got synced
rm -rf .repo & # lets remove unnecessary things, so that no storage issue can occur

# Normal build steps
source build/envsetup.sh
lunch omni_violet-eng
export LC_ALL="C"
export ALLOW_MISSING_DEPENDENCIES=true
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 20G
ccache -o compression=true
ccache -z
mka recoveryimage
curl bashupload.com -T out/target/product/violet/*zip
curl bashupload.com -T out/target/product/violet/*img
